### ISSUE TITLE
TypeError: Cannot assign to read-only property "Promise"

### ISSUE THREAD

**Issue by nd2s** [marmelab/restful.js#49]
Getting this error message when trying to run the library in Qt/QML. Looks like the runtime has some properties set to read-only.

Unfortunately I can't see the exact location of the problem, because I only have the minified library version.

Do you have any ideas?

**Comment by nd2s** [comment]
Just found non-monified version from #44 - problem is here:
https://github.com/abhishekisnot/restful.js/blob/5c2acb1a548d54614cdbd64727e11029ccf51a11/dist/restful.js#L2916

**Comment by RobinBressan** [comment]
Hi, we've just released a new version of restful.js, and now we use native promise. The polyfill is no longer embedded into the lib. The line you mention comes from this same polyfill. You should give a try to the new version and check if your issue is fixed or not.

**Comment by nd2s** [comment]
Thanks for your answer!

I had to modify restful.js to be able to import the library: had to get rid of the factory assignment to the `root` object and am assigning `factory()` to a global `restful` variable now to be able to access it.

There is no promise error anymore, unfortunately there's still a problem. `whatwg-fetch` does *not* work in qml because it's using `self`, which is only available in browsers (so the whole `restful.standalone.js` can't be used).

I don't understand how these fetch backends work. Is there any documentation available? Maybe I can modify `whatwg-fetch` then.

**Comment by RobinBressan** [comment]
Hi,

HTTP Backends have responsibility of performing HTTP requests based on an input config. We use fetch in the browser and request in Node.js.

I've made a little PR (#52) to add some doc about it.
